import { Request, Response } from 'express';
import prisma from '../lib/prisma.js';

export const getSignalPage = async (req: Request, res: Response) => {
    const { slug } = req.params;

    if (typeof slug !== 'string') {
        return res.status(400).send('Invalid slug');
    }

    try {
        const signalPage = await prisma.signalPage.findUnique({
            where: { slug },
            include: { urls: true },
        }) as any;

        if (!signalPage) {
            return res.status(404).send('Signal page not found');
        }

        // Return a bot-friendly HTML page
        const linksHtml = signalPage.urls
            .map((u: any) => `<li><a href="${u.url}">${u.url}</a></li>`)
            .join('\n');

        const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Discovery Signal - ${slug}</title>
        <meta name="robots" content="index,follow">
      </head>
      <body>
        <h1>Latest Verified Indexing Activity</h1>
        <p>The following resources have been processed and are being signaled for discovery.</p>
        <ul>
          ${linksHtml}
        </ul>
        <hr>
        <footer>Generated by Rocket-Indexer Core</footer>
      </body>
      </html>
    `;

        res.header('Content-Type', 'text/html');
        res.send(html);
    } catch (error) {
        res.status(500).send('Error loading signal page');
    }
};
